name: iita_bbest_app
description: "IITA BBEST Agricultural Products E-commerce Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  
  # State management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # UI and UX
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  animate_do: ^3.3.4
  page_transition: ^2.1.0
  smooth_page_indicator: ^1.2.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.0
  equatable: ^2.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  path: ^1.9.0
  path_provider: ^2.1.4
  
  # Navigation
  go_router: ^14.2.7
  
  # Forms and validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0
  
  # HTTP and API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local storage
  sqflite: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Icons & Splash
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/iita_logo.jpeg
    - assets/animations/
    - assets/icons/iita_logo.webp
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/iita_logo.webp"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/iita_logo.webp"
    background_color: "#FF6B35"
    theme_color: "#2E7D32"
  windows:
    generate: true
    image_path: "assets/icons/iita_logo.webp"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/iita_logo.webp"

flutter_native_splash:
  color: "#FF6B35"
  image: "assets/images/iita_logo.jpeg"
  color_dark: "#2E7D32"
  image_dark: "assets/images/iita_logo.jpeg"
  android_12:
    image: "assets/images/iita_logo.jpeg"
    color: "#FF6B35"
  web: true
